version: '3'

services:
  webapp:
    container_name: study-graphql-app
    build: .
    volumes:
      - ./study_graphql_app.pl:/usr/src/app/study_graphql_app.pl
      - ./schema.graphql:/usr/src/app/schema.graphql
      - ./studies.json:/usr/src/app/studies.json
    ports:
      - 4000:3000
    restart: always
    command: morbo -w schema.graphql study_graphql_app.pl # for development
    # command: hypnotoad -f study_graphql_app.pl            # for production


